name = "nuvei-api-emulator"
main = "src/worker.ts"
compatibility_date = "2024-12-01"

[assets]
directory = "./frontend/dist"

# Local Development settings
[dev]
port = 8787

# Production Environment (main branch)
[env.production]
name = "nuvei-api-emulator"
route = "nuvei-api-emulator.ndocs.workers.dev/*"

# Development/Staging Environment (develop branch)
[env.development]
name = "nuvei-api-emulator-development"
route = "nuvei-api-emulator-development.ndocs.workers.dev/*"
